service: aws-lambda-booking

provider: 
  name: aws
  runtime: nodejs10.x
  memorySize: 512
  timeout: 10
  stage: production
  region: us-west-2

functions: 
  apiBooking:
    handler: lambda.handler
    events:
      - http: ANY /{proxy+}
      - http: ANY /